version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: automadetech-n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
